name: Build Kernel

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          path: source

      - name: Checkout Tooltrain
        uses: actions/checkout@v4
        with:
          repository: hivejazzes/toolchain_samsung_sm8750
          path: toolchain_samsung_sm8750

      - run: ls toolchain_samsung_sm8750/kernel_platform/prebuilts

      - name: Install Prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y git tar wget bison zip

      - name: Download Clang
        run: |
          cd toolchain_samsung_sm8750/kernel_platform/prebuilts
          wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r522817.tar.gz && mkdir clang-r522817 && tar -xzf clang-r522817.tar.gz -C clang-r522817
          cd ../../..

      - name: Build
        run: |
          cd source
          export LTO=thin
          ./build.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kernel
          path: |
            source/out/arch/arm64/boot/Image

      - name: Collect zip name
        run: |
          echo "zip_name=$(basename -s .zip source/out/AnyKernel3/*.zip)" >> $GITHUB_ENV

      - name: Pack AnyKernel3
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.zip_name }}
          path: |
            source/out/AnyKernel3/*
            !source/out/AnyKernel3/*.zip
